
const music = [
  "Queencard - (G)I-DLE",
  "Spicy - aespa",
  "I AM - IVE",
  "UNFORGIVEN - LE SSERAFIM",
  "Eve, Psyche & The Bluebeard’s Wife - LE SSERAFIM",
  "Kitsch - IVE",
  "Super - SEVENTEEN",
  "Flower - JISOO",
  "Hype Boy - NewJeans",
  "ETA - NewJeans",
  "Love Lee - AKMU",
  "Ditto - NewJeans",
  "OMG - NewJeans",
  "Cupid - FIFTY FIFTY",
  "I Don’t Understand But I Luv U - SEVENTEEN",
  "ASAP - NewJeans",
  "Attention - NewJeans",
  "Pink Venom - BLACKPINK",
  "ANTIFRAGILE - LE SSERAFIM",
  "Candy - NCT DREAM",
  "Girls - aespa",
  "Fighting - BSS (SEVENTEEN) feat. Lee Young Ji",
  "Strawberry Moon - IU",
  "Still Life - BIGBANG",
  "INVU - TAEYEON",
  "After LIKE - IVE",
  "Eleven - IVE",
  "Attention - NewJeans",
  "Step Back - GOT the beat",
  "Rollin' - Brave Girls",
  "Celebrity - IU",
  "Dynamite - BTS",
  "Permission to Dance - BTS",
  "LILAC - IU",
  "Blueming - IU",
  "Weekend - TAEYEON",
  "Not Shy - ITZY",
  "Next Level - aespa",
  "In The Morning - ITZY",
  "Alcohol-Free - TWICE",
  "Peaches - Kai",
  "Savage - aespa",
  "Dolphin - Oh My Girl",
  "Lovesick Girls - BLACKPINK",
  "ON - BTS",
  "How You Like That - BLACKPINK",
  "Life Goes On - BTS",
  "More & More - TWICE",
  "What Type of X - Jessi",
  "Psycho - Red Velvet",
  "MAGO - GFRIEND",
  "NONSTOP - Oh My Girl",
  "Make A Wish - NCT U",
  "Cool - Weki Meki",
  "NUNU NANA - Jessi",
  "Dun Dun Dance - Oh My Girl",
  "Star - LOONA",
  "Stay Tonight - CHUNG HA",
  "You Calling My Name - GOT7",
  "Monster - Red Velvet - IRENE & SEULGI",
  "Dumb Dumb - JEON SOMI",
  "Nakka - AKMU feat. IU",
  "BBoom BBoom - MOMOLAND",
  "We Ride - Brave Girls",
  "Beautiful Beautiful - ONF",
  "Oh My God - (G)I-DLE",
  "Starlight - Taeyeon",
  "Playing With Fire - BLACKPINK",
  "HIP - MAMAMOO",
  "Oh! - Girls' Generation",
  "Gee - Girls' Generation",
  "Ddu-Du Ddu-Du - BLACKPINK",
  "Tempo - EXO",
  "Fake Love - BTS",
  "Run - BTS",
  "Lovesick Girls - BLACKPINK",
  "Only - Lee Hi",
  "Celebrity - IU",
  "Blueming - IU",
  "Love Scenario - iKON",
  "Don't Know What To Do - BLACKPINK",
  "Palette - IU feat. G-DRAGON",
  "Bbibbi - IU",
  "2002 - Anne-Marie",
  "Kill This Love - BLACKPINK",
  "Fiesta - IZ*ONE",
  "Dance The Night Away - TWICE",
  "Feel Special - TWICE",
  "Yes Or Yes - TWICE",
  "TT - TWICE",
  "Cheer Up - TWICE",
  "Knock Knock - TWICE",
  "Red Flavor - Red Velvet",
  "Psycho - Red Velvet",
  "Likey - TWICE",
  "Fancy - TWICE",
  "Heart Shaker - TWICE",
  "What is Love? - TWICE",
  "Signal - TWICE",
  "I Can't Stop Me - TWICE"
];


const randomMusic = music[Math.floor(Math.random() * music.length)];
document.getElementById('music-display').textContent = randomMusic;


function navigateTo(page) {
    window.location.href = page;
}